LANGUAGES={
"English":{
"app_title":"BackgroundPXR","tagline":"Power eXtreme Remover  •  AI background removal, made simple.","files_project":"FILES & PROJECT","add_images":"Add Images","add_folder":"Add Folder","drop_here":"Drag & drop images here\nor click to browse","quick_presets":"QUICK PRESETS","preset_product":"Product","preset_portrait":"Portrait","preset_object":"Object","preset_transparent":"Transparent","project_files":"PROJECT FILES","clear_all":"Clear All",
"pan":"Pan","zoom_out":"Zoom Out","zoom_in":"Zoom In","fit":"Fit","restore":"Restore","erase":"Erase","undo":"Undo","redo":"Redo","before":"Before","after":"After","fit_all":"Fit All","project_count":"{count} image(s) in project",
"ai_removal":"AI REMOVAL","ai_sub":"Remove background with AI","model":"Model","output":"Output","model_hq":"High Quality v2","model_quality":"Quality","model_fast":"Fast","model_portrait":"Portrait","bg_transparent":"Transparent Background","bg_white":"White Background","bg_color":"Custom Color","bg_image":"Background Image","bg_blur":"Blur Original","remove_bg":"Remove Background","color":"Color","background_image":"Image",
"refine_edges":"REFINE EDGES","edge_refinement":"Edge refinement","feather":"Feather","contrast":"Contrast","alpha_matting":"Fine hair / alpha matting","soft_shadow":"Soft shadow","auto_crop":"Auto crop","padding":"Padding",
"manual_cleanup":"MANUAL CLEANUP","manual_sub":"Fix leftovers without rerunning AI","smart_cleanup":"Smart Cleanup","remove_islands":"Remove Leftovers","reset_mask":"Reset Mask","brush_size":"Brush size","brush_hardness":"Brush hardness","run_ai_first":"Run AI removal first, then use Restore or Erase.","mask_edit_mode":"Manual mask view — paint directly on the subject mask.","cleanup_done":"Smart cleanup applied. Undo is available.","islands_done":"Removed {count} small leftover region(s). Undo is available.",
"export":"EXPORT","export_sub":"Save your result","format":"Format","canvas_size":"Canvas Size","canvas_original":"Original Size","canvas_square":"Square 1:1","canvas_portrait":"Portrait 4:5","canvas_story":"Story 9:16","canvas_landscape":"Landscape 16:9","canvas_product":"Product 2000×2000","suffix":"Filename Suffix","output_folder":"Output Folder","export_image":"Export Image","process_all":"Process All","open_folder":"Open Folder","auto_open":"Open folder after export",
"local_badge":"100% Local Processing","private_badge":"No Account","batch_badge":"Batch Mode","ready":"Ready","starting":"Starting PXR AI engine…","processing":"Processing {current}/{total}: {name}","saved":"Saved: {name}","complete":"Finished: {ok} saved, {fail} failed.","failed":"Failed: {name}","cancel":"Cancel","no_files":"Add at least one image first.","no_output":"Choose an output folder first.","choose_background":"Choose a background image first.","no_result":"Remove the background first.","error":"Error","all_images":"Image files","bg_files":"Background images","footer_left":"BackgroundPXR v{version}  |  Power eXtreme Remover  |  Remove. Replace. Create.","footer_by":"by Swir","footer_github":"github.com/Swir"},
"Polski":{
"app_title":"BackgroundPXR","tagline":"Power eXtreme Remover  •  Profesjonalne usuwanie tła AI.","files_project":"PLIKI I PROJEKT","add_images":"Dodaj zdjęcia","add_folder":"Dodaj folder","drop_here":"Przeciągnij zdjęcia tutaj\nlub kliknij, aby wybrać","quick_presets":"SZYBKIE PRESETY","preset_product":"Produkt","preset_portrait":"Portret","preset_object":"Obiekt","preset_transparent":"Przezroczyste","project_files":"PLIKI PROJEKTU","clear_all":"Wyczyść",
"pan":"Przesuń","zoom_out":"Oddal","zoom_in":"Przybliż","fit":"Dopasuj","restore":"Przywróć","erase":"Usuń","undo":"Cofnij","redo":"Ponów","before":"Przed","after":"Po","fit_all":"Dopasuj","project_count":"Zdjęć w projekcie: {count}",
"ai_removal":"USUWANIE AI","ai_sub":"Usuń tło za pomocą AI","model":"Model","output":"Wynik","model_hq":"Najwyższa jakość v2","model_quality":"Jakość","model_fast":"Szybki","model_portrait":"Portret","bg_transparent":"Przezroczyste tło","bg_white":"Białe tło","bg_color":"Własny kolor","bg_image":"Obraz tła","bg_blur":"Rozmyj oryginał","remove_bg":"Usuń tło","color":"Kolor","background_image":"Obraz",
"refine_edges":"DOPRACUJ KRAWĘDZIE","edge_refinement":"Rozszerz / zwęź maskę","feather":"Miękkość","contrast":"Kontrast maski","alpha_matting":"Włosy / alpha matting","soft_shadow":"Miękki cień","auto_crop":"Auto kadrowanie","padding":"Margines",
"manual_cleanup":"RĘCZNE POPRAWKI","manual_sub":"Usuń resztki bez ponownego AI","smart_cleanup":"Smart Cleanup","remove_islands":"Usuń resztki","reset_mask":"Reset maski","brush_size":"Rozmiar pędzla","brush_hardness":"Twardość pędzla","run_ai_first":"Najpierw usuń tło AI, potem użyj Przywróć lub Usuń.","mask_edit_mode":"Tryb maski — malujesz bezpośrednio po masce obiektu.","cleanup_done":"Smart Cleanup zastosowany. Możesz użyć Cofnij.","islands_done":"Usunięto małych obszarów: {count}. Możesz użyć Cofnij.",
"export":"EKSPORT","export_sub":"Zapisz gotowy wynik","format":"Format","canvas_size":"Rozmiar płótna","canvas_original":"Oryginalny rozmiar","canvas_square":"Kwadrat 1:1","canvas_portrait":"Portret 4:5","canvas_story":"Relacja 9:16","canvas_landscape":"Poziomo 16:9","canvas_product":"Produkt 2000×2000","suffix":"Dopisek nazwy","output_folder":"Folder zapisu","export_image":"Eksportuj zdjęcie","process_all":"Przetwórz wszystkie","open_folder":"Otwórz folder","auto_open":"Otwórz folder po eksporcie",
"local_badge":"100% lokalnie","private_badge":"Bez konta","batch_badge":"Tryb batch","ready":"Gotowy","starting":"Uruchamianie silnika PXR AI…","processing":"Przetwarzanie {current}/{total}: {name}","saved":"Zapisano: {name}","complete":"Zakończono: {ok} zapisano, {fail} błędów.","failed":"Błąd: {name}","cancel":"Anuluj","no_files":"Najpierw dodaj zdjęcie.","no_output":"Wybierz folder zapisu.","choose_background":"Wybierz obraz tła.","no_result":"Najpierw usuń tło.","error":"Błąd","all_images":"Pliki graficzne","bg_files":"Obrazy tła","footer_left":"BackgroundPXR v{version}  |  Power eXtreme Remover  |  Usuń. Podmień. Twórz.","footer_by":"by Swir","footer_github":"github.com/Swir"}}

def tr(language:str,key:str,**kwargs)->str:
    table=LANGUAGES.get(language,LANGUAGES["English"]); text=table.get(key,LANGUAGES["English"].get(key,key)); return text.format(**kwargs) if kwargs else text
